config_version = 14

[bar.default]
capsule = true
capsule_padding = 7.0
capsule_radius = 4
capsule_thickness = 0.74999998696148396
center = [ "tray", "clock" ]
end = [ "media", "notifications", "network", "group:g1", "battery", "session" ]
font_family = "Fira Mono"
margin_ends = 30
padding = 8
position = "left"
radius = 8
scale = 0.85000000521540642
start = [ "control-center", "launcher", "wallpaper", "workspaces" ]
thickness = 35
widget_spacing = 4

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "volume", "brightness" ]
    opacity = 1.0
    padding = 8.0
    radius = 4.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 656.0
    cy = 610.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 112.0
    box_width = 256.0
    cx = 640.0
    cy = 320.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = false
        clock_style = "digital"
        font_family = "Fira Code Medium"

[nightlight]
enabled = true

[plugins]
enabled = [ "noctalia/kaomoji", "noctalia/translator" ]

[shell]
screen_time_enabled = true

    [shell.shadow]
    direction = "right"

[theme]
community_palette = "Catppuccin Mocha Pink"
source = "community"

[wallpaper.default]
path = "/home/manuel/Pictures/Wallpapers/clouds-3.png"

[wallpaper.last]
path = "/home/manuel/Pictures/Wallpapers/clouds-3.png"

[wallpaper.monitors.eDP-1]
path = "/home/manuel/Pictures/Wallpapers/clouds-3.png"

[widget.battery]
display_mode = "graphic"
hide_when_full = true
hide_when_plugged = true

[widget.network]
icon_color = "tertiary"

[widget.tray]
hidden = [ "Network", "Blueman" ]