#!/bin/bash

get_env() {
    local env_var=$1
    local env_value=$(kwallet-query -f ENV_VARIABLES kdewallet -r $env_var 2>/dev/null)
    if [ -z "$env_value" ]; then
        echo "Error: Environment variable $env_var not found in kwallet."
        exit 1
    fi
    echo $env_value
}

get_env "$@"
