input {
	kb_layout = it
	# kb_options = grp:alt_shift_toggle
	repeat_delay = 500
    repeat_rate = 50
}

bind = Super, J, togglesplit
binde = Super, Plus, splitratio, 0.1

monitor = , preferred, auto, 1
monitor = DP-1, 1920x1080@60, auto, 1
